name: Check workflow files

on:
  pull_request:
    paths:
      - .github/workflows/*
      - .github/actions/*
      - aqua.yaml

jobs:
  check-workflow-files:
    timeout-minutes: 10
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setting up aqua
        uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.56.7

      - name: Run actionlint
        run: actionlint

      - name: Run ghalint
        run: |
          ghalint run
          ghalint run-action